import React, { useState, useEffect } from 'react';
import {
  Modal, View, Text, StyleSheet, ScrollView,
  TouchableOpacity, ActivityIndicator, SafeAreaView,
} from 'react-native';
import * as Speech from 'expo-speech';
import { Ionicons } from '@expo/vector-icons';
import { deepDive } from '../lib/railwayApi';
import { colors, radius, spacing, type } from '../theme';

export default function DeepDiveModal({ visible, onClose, attraction }) {
  const [text, setText] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [speaking, setSpeaking] = useState(false);

  useEffect(() => {
    if (!visible || !attraction) return;
    setText(null);
    setError(null);
    setSpeaking(false);
    Speech.stop();
    setLoading(true);
    deepDive({
      name: attraction.name,
      region: attraction.region,
      category: attraction.category,
      existing: attraction.commentary || attraction.short || '',
      tags: attraction.tags || [],
    })
      .then((r) => setText(r.text))
      .catch((e) => setError(e.message || 'Something went wrong'))
      .finally(() => setLoading(false));
  }, [visible, attraction?.id]);

  const handleClose = () => {
    Speech.stop();
    setSpeaking(false);
    onClose();
  };

  const toggleSpeak = () => {
    if (speaking) {
      Speech.stop();
      setSpeaking(false);
    } else {
      setSpeaking(true);
      Speech.speak(text, {
        rate: 0.9,
        pitch: 1,
        onDone: () => setSpeaking(false),
        onError: () => setSpeaking(false),
      });
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={handleClose}
    >
      <SafeAreaView style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.eyebrow}>🎙 DEEP DIVE</Text>
          <Text style={styles.title} numberOfLines={2}>{attraction?.name}</Text>
          <TouchableOpacity style={styles.closeBtn} onPress={handleClose}>
            <Ionicons name="close" size={24} color={colors.text} />
          </TouchableOpacity>
        </View>

        {loading && (
          <View style={styles.center}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={styles.loadingText}>
              Claude is researching{'\n'}{attraction?.name}…
            </Text>
            <Text style={styles.loadingHint}>This takes about 10–15 seconds</Text>
          </View>
        )}

        {!!error && (
          <View style={styles.center}>
            <Ionicons name="warning-outline" size={44} color={colors.danger} />
            <Text style={styles.errorText}>{error}</Text>
            <TouchableOpacity
              style={styles.retryBtn}
              onPress={() => {
                setError(null);
                setLoading(true);
                deepDive({
                  name: attraction.name,
                  region: attraction.region,
                  category: attraction.category,
                  existing: attraction.commentary || attraction.short || '',
                  tags: attraction.tags || [],
                })
                  .then((r) => setText(r.text))
                  .catch((e) => setError(e.message))
                  .finally(() => setLoading(false));
              }}
            >
              <Text style={styles.retryBtnText}>Try again</Text>
            </TouchableOpacity>
          </View>
        )}

        {!!text && (
          <>
            <ScrollView
              style={styles.scroll}
              contentContainerStyle={styles.scrollContent}
              showsVerticalScrollIndicator={false}
            >
              <Text style={styles.narration}>{text}</Text>
              <Text style={styles.poweredBy}>Generated by Claude · Anthropic</Text>
            </ScrollView>
            <View style={styles.footer}>
              <TouchableOpacity
                style={[styles.speakBtn, speaking && styles.speakBtnStop]}
                onPress={toggleSpeak}
                activeOpacity={0.85}
              >
                <Ionicons
                  name={speaking ? 'stop-circle-outline' : 'play-circle-outline'}
                  size={22}
                  color="white"
                />
                <Text style={styles.speakBtnText}>
                  {speaking ? 'Stop reading' : 'Read aloud'}
                </Text>
              </TouchableOpacity>
            </View>
          </>
        )}
      </SafeAreaView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  header: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    paddingRight: 56,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: colors.primary,
    marginBottom: 4,
  },
  title: { fontSize: 22, fontWeight: '700', color: colors.text },
  closeBtn: { position: 'absolute', top: spacing.md, right: spacing.md, padding: 6 },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
  },
  loadingText: {
    fontSize: 16,
    color: colors.muted,
    textAlign: 'center',
    lineHeight: 24,
    marginTop: spacing.md,
  },
  loadingHint: { fontSize: 13, color: colors.border, textAlign: 'center' },
  errorText: { fontSize: 15, color: colors.danger, textAlign: 'center', lineHeight: 22 },
  retryBtn: {
    marginTop: spacing.sm,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  retryBtnText: { color: colors.primary, fontWeight: '700' },
  scroll: { flex: 1 },
  scrollContent: { padding: spacing.lg, paddingBottom: spacing.xxl },
  narration: { fontSize: 16, lineHeight: 27, color: colors.text },
  poweredBy: {
    marginTop: spacing.xl,
    fontSize: 12,
    color: colors.border,
    textAlign: 'center',
  },
  footer: {
    padding: spacing.lg,
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  speakBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: radius.md,
  },
  speakBtnStop: { backgroundColor: '#C62828' },
  speakBtnText: { color: 'white', fontWeight: '700', fontSize: 16 },
});
